Bug #50648: univention.admin.modules: make EA_LAyout comparable in Python 3
Note: this looks broken in python 2: cmp() or cmp()

Thanks to Philipp:
Fix logic errors in comparison and always use rich comparison, which is
available since Python 2.6

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 412, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 625, in _doit
    univention.admin.modules.init(lo, position, module)
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 203, in init
    update_extended_attributes(lo, module, position)
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 553, in update_extended_attributes
    priofields = sorted(priofields)
TypeError: unorderable types: EA_Layout() < EA_Layout()