handlers: Convert ipaddr -> ipaddress
and remove u.a.ipaddress as admin/handler/__init__.py is finally
converted.

squash! handlers: Convert ipaddr -> ipaddress

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 738, in _doit
    out.extend(object_input(module, object, input, append=append))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 388, in object_input
    object[key] = value
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 3293, in __setitem__
    subnet = IPv4Network(u"%(subnet)s/%(subnetmask)s" % network_object, strict=False)
NameError: name 'IPv4Network' is not defined

...

squash! handlers: Convert ipaddr -> ipaddress

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 845, in _doit
    object = univention.admin.objects.get(module, co, lo, position='', dn=dn)
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 108, in get
    obj = univention.admin.modules.lookup(module.module, co, lo, base=dn, superordinate=superordinate, scope='base', unique=True, required=True)[0]
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 931, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1743, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/computers/__base.py", line 64, in __init__
    univention.admin.handlers.simpleComputer.__init__(self, co, lo, position, dn, superordinate, attributes)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1870, in __init__
    ips = [ip_address(u'%s' % (addr,)).exploded for key in ('aRecord', 'aAAARecord') for addr in self.oldattr.get(key, [])]
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1870, in <listcomp>
    ips = [ip_address(u'%s' % (addr,)).exploded for key in ('aRecord', 'aAAARecord') for addr in self.oldattr.get(key, [])]
  File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: "b'10.200.27.80'" does not appear to be an IPv4 or IPv6 address

squash! handlers: Convert ipaddr -> ipaddress

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 987, in _doit
    object.open()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/computers/__base.py", line 68, in open
    univention.admin.handlers.simpleComputer.open(self)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1990, in open
    zones.append((zoneName, [ip_address(x).exploded for x in attr[key]]))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1990, in <listcomp>
    zones.append((zoneName, [ip_address(x).exploded for x in attr[key]]))
  File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: b'10.200.27.80' does not appear to be an IPv4 or IPv6 address

squash! handlers: Convert ipaddr -> ipaddress

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/admincli/admin.py", line 1130, in <module>
    print('\n'.join(doit(sys.argv)))
  File "/usr/lib/python2.7/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python2.7/dist-packages/univention/admincli/admin.py", line 987, in _doit
    object.open()
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/computers/__base.py", line 68, in open
    univention.admin.handlers.simpleComputer.open(self)
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/__init__.py", line 1990, in open
    zones.append((zoneName, [ip_address(x.decode('ASCII')).exploded for x in attr[key]]))
KeyError: 'aAAARecord'

squash! handlers: Convert ipaddr -> ipaddress

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 738, in _doit
    out.extend(object_input(module, object, input, append=append))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 388, in object_input
    object[key] = value
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 3293, in __setitem__
    subnet = IPv4Network(u"%(subnet)s/%(subnetmask)s" % network_object, strict=False)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 492, in __getitem__
    elif key not in self.__no_default and self.descriptions[key].editable:
KeyError: 'subnet'