Bug #50648: fix decoding of mapped values for use in LDAP filters
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 844, in _doit
    object = univention.admin.objects.get(module, co, lo, position='', dn=dn)
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 108, in get
    obj = univention.admin.modules.lookup(module.module, co, lo, base=dn, superordinate=superordinate, scope='base', unique=True, required=True)[0]
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 931, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1746, in lookup
    filter_str = six.text_type(filter_s or u'')
  File "/usr/lib/python3/dist-packages/univention/admin/filter.py", line 68, in __str__
    return '(%s%s)' % (self.type, ''.join(map(six.text_type, self.expressions)))
  File "/usr/lib/python3/dist-packages/univention/admin/filter.py", line 132, in __str__
    return self.escape('(%s=%s)', (self.variable, self.value))
  File "/usr/lib/python3/dist-packages/univention/admin/filter.py", line 136, in escape
    return filter_format(string, args)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in filter_format
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in <genexpr>
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 41, in escape_filter_chars
    s = assertion_value.replace('\\', r'\5c')
TypeError: a bytes-like object is required, not 'str'