Bug #50648: settings/portal_entry: fix mapping
python3 /usr/lib/python3/dist-packages/univention/admincli/admin.py settings/portal_entry list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 1129, in <module>
    print('\n'.join(doit(sys.argv)))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 983, in _doit
    for object in univention.admin.modules.lookup(module, co, lo, scope='sub', superordinate=superordinate, base=position.getDn(), filter=filter):
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 934, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1751, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 235, in __init__
    oldinfo = self.mapping.unmapValues(self.oldattr)
  File "/usr/lib/python3/dist-packages/univention/admin/mapping.py", line 569, in unmapValues
    info = mapDict(self, oldattr)
  File "/usr/lib/python3/dist-packages/univention/admin/mapping.py", line 628, in mapDict
    v = mapping.unmapValue(key, value)
  File "/usr/lib/python3/dist-packages/univention/admin/mapping.py", line 563, in unmapValue
    return unmap_value(value, **kwargs) if unmap_value else value
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/settings/portal_entry.py", line 169, in unmapTranslationValue
    return [val.split(' ', 1) for val in vals]
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/settings/portal_entry.py", line 169, in <listcomp>
    return [val.split(' ', 1) for val in vals]
TypeError: a bytes-like object is required, not 'str'